version: '3'
services:
  app:
    container_name: full_app
    build:
      context: .
      dockerfile: cmd/app/Dockerfile
    ports:
      - 8080:8080
      - 50051:50051
    restart: on-failure
    env_file:
      - .env

    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-mysql
      - beanstalkd
    networks:
      - fullstack

  manager:
    container_name: manager_app
    build:
      context: .
      dockerfile: cmd/manager/Dockerfile
    env_file:
      - .env
    environment:
      - NUMBER_OF_WORKERS=${NUMBER_OF_WORKERS}
    restart: on-failure
    depends_on:
      - app
      - beanstalkd
    networks:
      - fullstack



  fullstack-mysql:
    image: mysql:8.0
    container_name: full_db_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/init_mysql
    networks:
      - fullstack

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - fullstack-mysql
    environment:
      - PMA_HOST=fullstack-mysql
      - PMA_USER=${DB_USER}
      - PMA_PORT=${DB_PORT}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 9090:80
    restart: on-failure
    networks:
      - fullstack

  beanstalkd:
    container_name: ddev-beanstalkd
    image: schickling/beanstalkd
    restart: "no"
    expose:
      - 11300
    ports:
      - 11300:11300
    labels:
      com.ddev.site-name: "sitename"
    volumes:
      - ".:/mnt/ddev_config"
    networks:
      - fullstack



volumes:
  api:
  database_mysql:

networks:
  fullstack:
    driver: bridge