// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: delete_account.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeleteAccountService_DeleteAccount_FullMethodName = "/proto.DeleteAccountService/DeleteAccount"
)

// DeleteAccountServiceClient is the client API for DeleteAccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeleteAccountServiceClient interface {
	DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error)
}

type deleteAccountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeleteAccountServiceClient(cc grpc.ClientConnInterface) DeleteAccountServiceClient {
	return &deleteAccountServiceClient{cc}
}

func (c *deleteAccountServiceClient) DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAccountResponse)
	err := c.cc.Invoke(ctx, DeleteAccountService_DeleteAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteAccountServiceServer is the server API for DeleteAccountService service.
// All implementations must embed UnimplementedDeleteAccountServiceServer
// for forward compatibility.
type DeleteAccountServiceServer interface {
	DeleteAccount(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error)
	mustEmbedUnimplementedDeleteAccountServiceServer()
}

// UnimplementedDeleteAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeleteAccountServiceServer struct{}

func (UnimplementedDeleteAccountServiceServer) DeleteAccount(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccount not implemented")
}
func (UnimplementedDeleteAccountServiceServer) mustEmbedUnimplementedDeleteAccountServiceServer() {}
func (UnimplementedDeleteAccountServiceServer) testEmbeddedByValue()                              {}

// UnsafeDeleteAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeleteAccountServiceServer will
// result in compilation errors.
type UnsafeDeleteAccountServiceServer interface {
	mustEmbedUnimplementedDeleteAccountServiceServer()
}

func RegisterDeleteAccountServiceServer(s grpc.ServiceRegistrar, srv DeleteAccountServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeleteAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeleteAccountService_ServiceDesc, srv)
}

func _DeleteAccountService_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeleteAccountServiceServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeleteAccountService_DeleteAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeleteAccountServiceServer).DeleteAccount(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeleteAccountService_ServiceDesc is the grpc.ServiceDesc for DeleteAccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeleteAccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DeleteAccountService",
	HandlerType: (*DeleteAccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteAccount",
			Handler:    _DeleteAccountService_DeleteAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delete_account.proto",
}
